# Generated by Django 4.2.4 on 2023-08-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='title',
            new_name='tasks',
        ),
    ]
